language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
services: mongodb
script: "python setup.py test"

# Note about Tornado 3:
#
# Futures were introduced in Python 3 in the `concurrent.futures` package.
# This package has also been backported to older versions of Python and can be
# installed with `pip install futures`. Tornado 3 on Python 2 uses
# concurrent.futures if available; otherwise it will use a compatible class
# defined in tornado.concurrent.
#
# Tornado 4 always uses its own futures.

env:
  - TORNADO=3 FUTURES=yes
  - TORNADO=3 FUTURES=no
  - TORNADO=4
matrix:
  exclude:
    # No one would install `concurrent.futures` on Python 3, I hope?
    - python: "3.3"
      env: TORNADO=3 FUTURES=yes
    # Tornado 3 lacks a fix for test errors related to GC and unclosed sockets.
    - python: "3.4"
      env: TORNADO=3 FUTURES=yes
    - python: "3.4"
      env: TORNADO=3 FUTURES=no
before_install:
  # Ensure tests don't start before MongoDB does.
  - python wait_for_mongodb.py 30
before_script:
  - if [[ "$FUTURES" == "yes" ]]; then pip install futures; fi
  - if [[ "$TORNADO" == "3" ]]; then pip install 'tornado>=3,<4'; fi
  - if [[ "$TORNADO" == "4" ]]; then pip install 'tornado>=4,<5'; fi

branches:
  only:
    - master
    - stable
