language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services: mongodb

install:
  - pip install tornado
  - pip install -e '.[encryption]'

script: "python setup.py test"

branches:
  only:
    - master
